resource_manifest_version '77731fab-63ca-442c-a67b-abc70f28dfa5'
 
files {
    'data/**/handling.meta',
    'data/**/vehicles.meta',
    'data/**/carvariations.meta',
    'data/**/carcols.meta',
    'data/**/vehiclelayouts.meta',
	'ELS/polrangerum.xml',
	'ELS/polrangerum.xml',
	'ELS/polrangerum.xml',
	'ELS/polbmwm5um.xml',
	'ELS/polbmweum.xml',
	'ELS/polaudis6um.xml',
	'ELS/pollandcruiserum.xml',
	'ELS/polaudis6um.xml',
	'ELS/polbmwx5um.xml',
	'308H.xml',
	'ELS/poltsgsprinter.xml',
	'ELS/bmw330d22.xml',
	'ELS/polsprinterarv.xml',
	'ELS/polsprinterarv.xml',
	'ELS/polvolxc90.xml',
	'ELS/polbmwx566.xml',
	'ELS/polbmwx570.xml',
	'ELS/poltransitarv.xml',
	'ELS/polshogunarv.xml',
	'ELS/polfordmon.xml',
	'ELS/polrangerum.xml',
	'ELS/polbmwm5um.xml',
	'ELS/polvolxc90.xml',
	'ELS/polastraum.xml',
	'ELS/polvolv40um.xml',
	'ELS/polbmw2sum.xml',
	'ELS/polbmwg31um.xml',
	'ELS/poltransitred.xml',
	'ELS/polvolxc90seg.xml',
	'ELS/polrangersegum.xml',
	'ELS/pollandseg.xml',
	'ELS/polrangerseg.xml',
	'ELS/polbikem.xml',
	'ELS/polbikew.xml',
	'ELS/polbmwestaterpu2.xml',
	'ELS/poljankel.xml',
	'ELS/polvolvoestaterpu.xml',
	'ELS/polv70rpu.xml',
	'ELS/polxc90rpuairport.xml',
	'ELS/polfordestaterpu.xml',
	'ELS/polbmwestaterpu1.xml',
	'ELS/poltransitirpu.xml',
	'ELS/pollandrover60.xml',
	'ELS/polaudis4.xml',
	'ELS/polx5rpu.xml',
	'ELS/polshogunrpu.xml',
	'ELS/poltransitpt.xml',
	'ELS/polg31area.xml',
	'ELS/poltransitcarrier.xml',
	'ELS/polmitsout.xml',
	'ELS/polmitsout.xml',
	'ELS/polkia.xml',
	'ELS/polastra.xml',
	'ELS/pol2ss.xml',
	'ELS/pol2sw.xml',
	'ELS/pol308.xml',
	'ELS/polbmwi3.xml',
	'ELS/polnavaraum.xml',
	'ELS/polxc90um.xml',
	'ELS/polbmw330um.xml',
	'ELS/polm135ium.xml',
	'ELS/hart3.xml',
	'ELS/hart1.xml',
	'ELS/las3.xml',
	'ELS/rrv2.xml',
	'ELS/hems1.xml',
	'ELS/lasbike.xml',
	'ELS/las5.xml',
	'ELS/las6.xml',
	'ELS/las7.xml'
}

data_file 'HANDLING_FILE'            'data/**/handling.meta'
data_file 'VEHICLE_METADATA_FILE'    'data/**/vehicles.meta'
data_file 'CARCOLS_FILE'             'data/**/carcols.meta'
data_file 'VEHICLE_VARIATION_FILE'   'data/**/carvariations.meta'
data_file 'VEHICLE_LAYOUTS_FILE'     'data/**/vehiclelayouts.meta'

is_els 'true'